### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by therealri** [Alabate/node-freefare#4]
Hi @Alabate,

Great work, really nice package ;)

I seem to be getting an error when trying to npm install.

Any suggestions on how I can overcome this?

I am running Node v6.10.0 and npm 3.10.10

[~/Desktop/freefare]$ npm install --save freefare

> freefare@0.1.3 install /Users/user/Desktop/freefare/node_modules/freefare
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/freefare/src/addon.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
In file included from ../src/addon.cpp:1:
../src/device.h:8:11: fatal error: 'nfc/nfc.h' file not found
        #include <nfc/nfc.h>
                 ^
1 warning and 1 error generated.
make: *** [Release/obj.target/freefare/src/addon.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/user/.nvm/versions/node/v6.10.0/bin/node" "/Users/user/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Desktop/freefare/node_modules/freefare
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN freefare-demo@1.0.0 No description
npm WARN freefare-demo@1.0.0 No repository field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/user/.nvm/versions/node/v6.10.0/bin/node" "/Users/user/.nvm/versions/node/v6.10.0/bin/npm" "install" "--save" "freefare"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! freefare@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freefare@0.1.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freefare package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freefare
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freefare
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Desktop/freefare/npm-debug.log
[~/Desktop/freefare]$

**Comment by therealri** [comment]
I am using macOS and trying reinstalling libfreefare using Homebrew, I got a different output error this time:

[~/Desktop/freefare]$ npm install --save freefare

> freefare@0.1.3 install /Users/user/Desktop/freefare/node_modules/freefare
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/freefare/src/addon.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
1 warning generated.
  CXX(target) Release/obj.target/freefare/src/freefare.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
1 warning generated.
  CXX(target) Release/obj.target/freefare/src/device.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
1 warning generated.
  CXX(target) Release/obj.target/freefare/src/tag.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
1 warning generated.
  CXX(target) Release/obj.target/freefare/src/tag_mifareultralight.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
1 warning generated.
  CXX(target) Release/obj.target/freefare/src/tag_mifareclassic.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
../src/tag_mifareclassic.cpp:319:27: warning: private field 'block' is not used [-Wunused-private-field]
        MifareClassicBlockNumber block;
                                 ^
../src/tag_mifareclassic.cpp:320:11: warning: private field 'amount' is not used [-Wunused-private-field]
        uint32_t amount;
                 ^
3 warnings generated.
  CXX(target) Release/obj.target/freefare/src/tag_mifaredesfire.o
In file included from <built-in>:355:
<command line>:8:9: warning: '_FILE_OFFSET_BITS' macro redefined [-Wmacro-redefined]
#define _FILE_OFFSET_BITS 32
        ^
<command line>:7:9: note: previous definition is here
#define _FILE_OFFSET_BITS 64
        ^
../src/tag_mifaredesfire.cpp:156:10: error: use of undeclared identifier 'htole32'
                        aid = htole32(aid);
                              ^
1 warning and 1 error generated.
make: *** [Release/obj.target/freefare/src/tag_mifaredesfire.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/user/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.5.0
gyp ERR! command "/Users/user/.nvm/versions/node/v6.10.0/bin/node" "/Users/user/.nvm/versions/node/v6.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/user/Desktop/freefare/node_modules/freefare
gyp ERR! node -v v6.10.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN freefare-demo@1.0.0 No description
npm WARN freefare-demo@1.0.0 No repository field.
npm ERR! Darwin 16.5.0
npm ERR! argv "/Users/user/.nvm/versions/node/v6.10.0/bin/node" "/Users/user/.nvm/versions/node/v6.10.0/bin/npm" "install" "--save" "freefare"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! freefare@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the freefare@0.1.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the freefare package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs freefare
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls freefare
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/Desktop/freefare/npm-debug.log

**Comment by Alabate** [comment]
Hi,

For your first message, It seems that your system was missing `nfc/nfc.h` which is LibNFC. When you install LibFreefare first, which should install LibNFC as a dependency.

For your second error, your system complains about missing `htole32()`, which is a linux-specific function that convert endianness.

I will try to fix it on another branch, so you can the fix :)

**Comment by therealri** [comment]
Thank you so much! :)

**Comment by Alabate** [comment]
Ok, you can try to use the new branch by replacing the `freefare` entry in your `package.json` by

```
    "freefare": "Alabate/node-freefare#bugfix/4-mac-compatibilty"
```

**Comment by therealri** [comment]
Thanks @Alabate,

I've replaced the entry and completed the npm install :)

There were a few warnings but it doesn't seem like anything to lose sleep over :)

Appreciate your time and assistance!

**Comment by Alabate** [comment]
Perfect, thank you for your issue :)

I've released this modification on NPM. You can put back the original entry in your `package.json`.

Feel free to post a new issue if you have any other problemes!
